File = "config.toml"

[channels]
  control = ""
  data = ""

[edgex]
  url = "http://localhost:48090/api/v1/"

[heartbeat]
  interval = "10s"

[log]
  level = "info"

[mqtt]
  ca_cert = ""
  ca_path = "ca.crt"
  cert_path = "thing.cert"
  client_cert = ""
  client_key = ""
  mtls = false
  password = ""
  priv_key_path = "thing.key"
  qos = 0
  retain = false
  skip_tls_ver = true
  url = "localhost:1883"
  username = ""

[server]
  nats_url = "nats://127.0.0.1:4222"
  port = "9998"

[terminal]
  session_timeout = "1m0s"
